Attribute VB_Name = "a_Properties"
Option Explicit

'-------------------------------------------------- TABLE & VIEW --------------------------------------------------
Public Const TABLE_ATTENDANCE = SCHEMA_OPSYSTEM & "db_attendance "
Public Const TABLE_CHURCH = SCHEMA_OPSYSTEM & "db_churchlist "
Public Const TABLE_CHURCH_CUSTOM = SCHEMA_OPSYSTEM & "db_churchlist_custom "
Public Const TEMP_CHURCHLIST_BY_TIME = SCHEMA_OPSYSTEM & "temp_churchlist_by_time "
Public Const TABLE_CHURCH_MAP = SCHEMA_OPSYSTEM & "db_church_map "
Public Const TABLE_COUNTRY = SCHEMA_OPSYSTEM & "db_country "
Public Const TABLE_GEODATA = SCHEMA_OPSYSTEM & "db_geodata "
Public Const TABLE_OVS_DEPT = SCHEMA_OPSYSTEM & "db_ovs_dept "
Public Const VIEW_PASTORAL_CAREER = SCHEMA_OPSYSTEM & "v_pstaff_detail_transfer " '--//선지자 상세정보 시트의 발령이력일 위한 VIEW
Public Const TABLE_PASTORALSTAFF = SCHEMA_OPSYSTEM & "db_pastoralstaff "
Public Const TABLE_PASTORALWIFE = SCHEMA_OPSYSTEM & "db_pastoralwife "
Public Const TABLE_PSTAFF = SCHEMA_OPSYSTEM & "db_pastoralstaff "
Public Const TABLE_POSITION = SCHEMA_OPSYSTEM & "db_position "
Public Const A_POSITION = SCHEMA_OPSYSTEM & "a_position "
Public Const VIEW_PSTAFF_INFORMATION = SCHEMA_OPSYSTEM & "v0_pstaff_information "
Public Const VIEW_PSTAFF_INFORMATION_ALL = SCHEMA_OPSYSTEM & "v0_pstaff_information_all "
Public Const TABLE_PSTAFF_PHOTO = SCHEMA_OPSYSTEM & "db_pastoralstaff_photo "
Public Const TABLE_SPECIAL_POSITION = SCHEMA_OPSYSTEM & "db_position2 "
Public Const A_SPECIAL_POSITION = SCHEMA_OPSYSTEM & "a_position2 "
Public Const TABLE_TITLE = SCHEMA_OPSYSTEM & "db_title "
Public Const A_TITLE = SCHEMA_OPSYSTEM & "a_title "
Public Const TABLE_TRANSFER = SCHEMA_OPSYSTEM & "db_transfer "
Public Const TABLE_USER = SCHEME_COMMON & "users "
Public Const TABLE_AUTH_TABLE = SCHEMA_OPSYSTEM & "a_auth_table "
Public Const TABLE_AUTHORITY = SCHEMA_OPSYSTEM & "a_authority "
Public Const TABLE_THEOLOGICAL = SCHEMA_OPSYSTEM & "db_theological "
Public Const TABLE_SERMON = SCHEMA_OPSYSTEM & "db_sermon "
Public Const TABLE_HISTORY_CHURCH_ESTABLISH = SCHEMA_OPSYSTEM & "db_history_church_establish "
Public Const TABLE_HISTORY_CHURCH = SCHEMA_OPSYSTEM & "db_history_church "
Public Const TABLE_VISA_PHOTO = SCHEMA_OPSYSTEM & "db_visa_photo "
Public Const TABLE_PASSPORT_PHOTO = SCHEMA_OPSYSTEM & "db_passport_photo "
